### ISSUE TITLE
Entity

### ISSUE THREAD

**Issue by rougsig** [slmlt/bgi#10]
Логика приложения зависит от BoardGame.
DB зависит от BoardGame.
В свою очередь BoardGame зависит от api сервера.
Получается если изменится апи, придется править db и логику сервера.

В таких ситуациях стоит разделять enitity, для каждого потребителя отдельно.
BoardGameNM (NetworkModel)
BoardGameUM (UiModel)
BoardGameSM (StorageModel) 

Да в начале они будут дублироваться, но обычно через месяц что-то да меняется. На старте можно сделать лайфХак, через `typealias`:
```
data class BoardGame

typealias BoardGameNM  = BoardGame
typealias BoardGameUM = BoardGame
typealias BoardGameSM = BoardGame
```

При изменении одной из частей удаляется `typealias` и пишется свой `data class`

**Comment by slmlt** [comment]
Согласен, что не очень хорошо, но мне кажется бороться с изменением api проще с помощью собственного прокси api (в этом проекте писать его нам запретили).
По поводу бд если честно не подумал, никогда раньше не сталкивался с тем, что изменение дата класса может вызвать проблему с бд.
Ну и в целом, dto вроде как более-менее общепринято скорее считается антипаттерном, я как-то привык думать, что такие проблемы при наличии прокси api решаются тайп конвертерами в бд и ретрофите.
Если рефакторить все-таки необходимо, я, если можно, отложу эту задачу на ближе к концу: рефакторинг 2 дата классов в 7 сломает весь проект и сделает его непонятным даже для меня :)

**Comment by rougsig** [comment]
>  прокси api 

Как правило его нету и приходиться жить, с очень кривым апи сервера, который часто меняется.

**Comment by rougsig** [comment]
Я бы советовал, хотя бы базу от api отделить, ты можешь захотеть на клиенте сделать любимые. А их на сервере например нету.
