### ISSUE TITLE
Вопрос про BoardGameHolder

### ISSUE THREAD

**Issue by Kortvk** [slmlt/bgi#14]
Почему `ImageView` генерируются динамически и добавляются в `LinearLayout` с `HorizontalScrollView`? Почему не использовать для этого `RecyclerView`?

**Comment by slmlt** [comment]
Динамически, потому что количество изображений может меняться и в общем случае не гарантировано. Ну и потому, что, 20 ImageView в разметке, вызывают во мне необъяснимую неприязнь, даже через include :) RecyclerView для объектов без иерархии на мой взгляд оверхэд, плюс предвижу проблемы с переиспользованием элементов. Возможно, конечно, что я глубоко не прав.

**Comment by Kortvk** [comment]
Руками точно не надо добавлять) Тут ты еще должен понимать, что это не очень эффективно в плане памяти. Если ты уверен, что картинок будет не очень много, то окей. Оставляй так. Но если вид будет усложняться, то не надо  использовать такое решение.

**Comment by slmlt** [comment]
Согласен, что с точки зрения эффективности это несколько печально. 
Максимальное количество картинок я как раз контролирую через запрос к api (сейчас 20), проблема в том, что никто не знает сколько их там в базе - может 1400, а может 3.  
Ну и косяк, что api для картинок отдельный и выдает картинки только для одной игры за раз. Какое решение было бы более оптимальным в моей ситуации? Ну, то есть если бы я знал точное число картинок и получал бы их скопом - я как-то думал, что можно только динамически или в разметке

**Comment by Kortvk** [comment]
Как ты можешь заметить, ты перед назначением картинок, чистишь ImageView и создаешь их заново с последующей инициализацией. Инфлейтить каждый раз вьюху очень дорогое удовольствие . В случае с RecyclerView он создает необходимое количество вьюх (так чтобы они заняли весь экран + еще пара итемов), а дальше будет просто их переставлять. Glide кэширует загруженные картинки, благодаря чему ты не качаешь постоянно картинки заново. Поэтому лучше используй recycler. Это, вполне, нормально

**Comment by slmlt** [comment]
Порефакторил в #19
