### ISSUE TITLE
Возможный баг с RecyclerView

### ISSUE THREAD

**Issue by Kortvk** [slmlt/bgi#20]
Файл `BoardGameHolder.kt`
```
if (game.image != null) {
            Glide.with(view).load(game.image).into(view.background_image)
        }
```
Здесь будет баг, если картинки не будет. Может случиться такое, что будет отрисовано другое изображение

**Comment by slmlt** [comment]
У меня даже было специальное изображение для этого случая, но я его забыл в код подставить. Исправлено в #30
