### ISSUE TITLE
NETWORK_EXCEPTIONS

### ISSUE THREAD

**Issue by rougsig** [slmlt/bgi#22]
```
val NETWORK_EXCEPTIONS: List<Class<*>> = Arrays.asList(
    UnknownHostException::class.java,
    SocketTimeoutException::class.java,
    ConnectException::class.java
)
```

Зачем оно? + так как оно используется только, что проверить наличие, лучше сделать `HashSet`

**Comment by slmlt** [comment]
Поменял на Set в #30 . Нужно, чтобы показывать сообщения в зависимости от ошибок. Пока до этого руки не дошли, так что оно прост

**Comment by rougsig** [comment]
Не знаю как апи выгялдит. Может у них есть нормальный ответ на ошибку? с errorId или чем-то таким.

**Comment by slmlt** [comment]
Неа, там все очень грустно
