### ISSUE TITLE
also let apply 

### ISSUE THREAD

**Issue by rougsig** [slmlt/bgi#26]
```
ImageView(view.context).also {
                it.layoutParams = imageViewParams
                it.scaleType = ImageView.ScaleType.FIT_XY
                it.adjustViewBounds = true
            }
```

тут по идее должен быть apply

Тут довольно хорошо описано, когда какую и почему. (eng)
https://medium.com/@elye.project/mastering-kotlin-standard-functions-run-with-let-also-and-apply-9cd334b0ef84

Хоть и сигнатура метода одинакова, логический смысл разный.

**Comment by slmlt** [comment]
Спасибо! Я правда, уже все порефакторил на RecyclerView (было в #19 ) и этой строчки теперь нету.

**Comment by rougsig** [comment]
Окей)
