### ISSUE TITLE
Верстка item_boardgame.xml

### ISSUE THREAD

**Issue by rougsig** [slmlt/bgi#29]
В верстку используется ConstraintLayout, ему как правило не нужны какие-либо дочерные Viewgroup, потому что детей можно позиционировать относительно друг друга.

**Comment by slmlt** [comment]
К сожалению, там это необходимость, чтобы добиться красивой обрезки изображения без танцев с бубном. Вложенный лейаут нужен, чтобы выставить отступы (если выставить в корневом, изображение не будет обрезано, а сместится в низ на отступ)

**Comment by rougsig** [comment]
Обрезка возможно. Но отступы точно можно сделать без вложенности.

**Comment by slmlt** [comment]
Я с этим к сожалению, затрудняюсь - было бы здорово получить совет куда копать. Если не выставить у родительского объекта margin, у вложенных в него объектов отступов не будет, как ни выставляй. А если у родительского выставить, обрезки не будет.

**Comment by rougsig** [comment]
https://developer.android.com/reference/android/support/constraint/Barrier ?

**Comment by slmlt** [comment]
Почитал барьер, но пришел к выводу что он мне никак не поможет. Видимо, имелся в виду guideline (про который я благополучно забыл, несмотря на то, что он есть у меня в соседнем лейауте). Вобщем, вложенность убрал :)
