### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by rougsig** [slmlt/bgi#9]
Используйте `Reformat code` перед коммитом
![default](https://user-images.githubusercontent.com/18681794/53818657-1a809700-3f71-11e9-9a6f-160d7adafa01.png)

**Comment by slmlt** [comment]
Странно, в проекте на коммитах галка Reformat стоит. Скриншот, кстати, из другого проекта. 
Можно уточнить, где именно проблема?

**Comment by rougsig** [comment]
Да скрин из другого проекта.
https://github.com/slmlt/bgi/blob/master/app/src/main/java/ru/appkode/kotlincourse/bgi/repository/LocalRepository.kt
https://github.com/slmlt/bgi/blob/master/app/src/main/java/ru/appkode/kotlincourse/bgi/repository/local/RoomRepository.kt

**Comment by slmlt** [comment]
Поправил в #16
